version: '2.1'
services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=pyventa
      - MYSQL_PASSWORD=Damasco
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=admin
      - DATABASE_USER=root
     #- DATABASE_PASSWORD=Damasco


#  backend:

    # image: "pyventa/wanda:latest"
    # build:
    #   context: ./backend
    #   dockerfile: backend.dockerfile

volumes:
  mysql_data:
    driver: local
