<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "productos".
 *
 * @property string $codigo
 * @property integer $ref
 * @property string $descripcion
 * @property integer $familia
 * @property double $costo
 * @property double $ganancia
 * @property double $precio
 * @property double $stock
 * @property integer $unidad
 * @property double $vendidas
 * @property integer $impuesto
 * @property string $ultima_modificacion
 * @property string $aliasModel
 */
abstract class Articulos extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'productos';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['codigo', 'familia', 'unidad', 'impuesto'], 'integer'],
            [['descripcion', 'familia', 'costo', 'ganancia', 'precio', 'stock', 'unidad', 'vendidas', 'impuesto', 'ultima_modificacion'], 'required'],
            [['costo', 'ganancia', 'precio', 'stock', 'vendidas'], 'number'],
            [['ultima_modificacion'], 'safe'],
            [['descripcion'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'codigo' => 'Codigo',
            'ref' => 'Ref',
            'descripcion' => 'Descripcion',
            'familia' => 'Familia',
            'costo' => 'Costo',
            'ganancia' => 'Ganancia',
            'precio' => 'Precio',
            'stock' => 'Stock',
            'unidad' => 'Unidad',
            'vendidas' => 'Vendidas',
            'impuesto' => 'Impuesto',
            'ultima_modificacion' => 'Ultima Modificacion',
        ];
    }




}
