<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cajas".
 *
 * @property integer $num_caja
 * @property string $nombre
 * @property string $maquina
 * @property double $saldo_inicial
 * @property string $estado
 * @property double $efectivo
 * @property string $aliasModel
 */
abstract class Cajas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cajas';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['num_caja', 'nombre', 'saldo_inicial', 'estado', 'efectivo'], 'required'],
            [['num_caja'], 'integer'],
            [['saldo_inicial', 'efectivo'], 'number'],
            [['estado'], 'safe'],
            [['nombre'], 'string', 'max' => 45],
            [['maquina'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'num_caja' => 'Num Caja',
            'nombre' => 'Nombre',
            'maquina' => 'Maquina',
            'saldo_inicial' => 'Saldo Inicial',
            'estado' => 'Estado',
            'efectivo' => 'Efectivo',
        ];
    }




}
