<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "clientes".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $rfc
 * @property string $direccion
 * @property string $poblacion
 * @property string $estado
 * @property string $tel
 * @property string $correo
 * @property integer $tipo
 * @property double $credito
 * @property string $aliasModel
 */
abstract class Clientes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'clientes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'rfc', 'direccion', 'poblacion', 'estado', 'tel', 'correo', 'tipo', 'credito'], 'required'],
            [['tipo'], 'integer'],
            [['credito'], 'number'],
            [['nombre'], 'string', 'max' => 150],
            [['rfc', 'tel'], 'string', 'max' => 15],
            [['direccion', 'poblacion', 'estado'], 'string', 'max' => 100],
            [['correo'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'rfc' => 'Rfc',
            'direccion' => 'Direccion',
            'poblacion' => 'Poblacion',
            'estado' => 'Estado',
            'tel' => 'Tel',
            'correo' => 'Correo',
            'tipo' => 'Tipo',
            'credito' => 'Credito',
        ];
    }




}
