<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "impuestos".
 *
 * @property integer $id
 * @property string $nombre
 * @property double $porcentaje
 * @property string $aliasModel
 */
abstract class Impuestos extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'impuestos';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'porcentaje'], 'required'],
            [['porcentaje'], 'number'],
            [['nombre'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'porcentaje' => 'Porcentaje',
        ];
    }




}
