<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "notas_cobradas".
 *
 * @property integer $id
 * @property integer $nota
 * @property string $aliasModel
 */
abstract class NotasCobradas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notas_cobradas';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nota'], 'required'],
            [['nota'], 'integer'],
            [['nota'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nota' => 'Nota',
        ];
    }




}
