<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "usuarios".
 *
 * @property integer $id_usuario
 * @property string $nombre
 * @property string $usuario
 * @property string $clave
 * @property integer $nivel
 * @property string $aliasModel
 */
abstract class Usuarios extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usuarios';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'usuario', 'clave'], 'required'],
            [['nivel'], 'integer'],
            [['nombre', 'usuario', 'clave'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_usuario' => 'Id Usuario',
            'nombre' => 'Nombre',
            'usuario' => 'Usuario',
            'clave' => 'Clave',
            'nivel' => 'Nivel',
        ];
    }




}
