<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "vendidos".
 *
 * @property integer $venta
 * @property integer $producto
 * @property integer $tipo
 * @property double $cantidad
 * @property double $total
 * @property string $aliasModel
 */
abstract class Vendidos extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vendidos';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['venta', 'producto', 'tipo', 'cantidad', 'total'], 'required'],
            [['venta', 'producto', 'tipo'], 'integer'],
            [['cantidad', 'total'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'venta' => 'Venta',
            'producto' => 'Producto',
            'tipo' => 'Tipo',
            'cantidad' => 'Cantidad',
            'total' => 'Total',
        ];
    }




}
