<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "ventas".
 *
 * @property string $fecha
 * @property double $subtotal
 * @property double $descuentos
 * @property double $total
 * @property double $efectivo
 * @property string $aliasModel
 */
abstract class Ventas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ventas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha', 'subtotal', 'descuentos', 'total', 'efectivo'], 'required'],
            [['fecha'], 'safe'],
            [['subtotal', 'descuentos', 'total', 'efectivo'], 'number'],
            [['fecha'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'fecha' => 'Fecha',
            'subtotal' => 'Subtotal',
            'descuentos' => 'Descuentos',
            'total' => 'Total',
            'efectivo' => 'Efectivo',
        ];
    }




}
